// ───────────────────────────────────────────────────────────────────
// MODULE: Pi Remote Protocol Public API
// ───────────────────────────────────────────────────────────────────

export const PROTOCOL_VERSION = 1 as const;

export { enrollmentProof, sessionProof } from './auth.js';
export {
  approvalActionDigest,
  canonicalizeApprovalAction,
  canonicalizeJson,
  sha256,
} from './approval.js';

export { RUNTIME_MODES } from './types.js';

export {
  isEnvelope,
  isAcceptEditsGrantDto,
  isApprovalAuthorityConsumeRequest,
  isApprovalAuthorityConsumeResponse,
  isApprovalAuthorityRequest,
  isApprovalAuthorityRequestResponse,
  isApprovalCardDto,
  isApprovalDecisionCommand,
  isApprovalDecisionResponse,
  isApprovalRequestedPayload,
  isApprovalResultPayload,
  isApplicationSessionResponse,
  isAttentionChangedPayload,
  isAttentionClass,
  isAttentionItemDto,
  isAttentionResolutionDto,
  isAvailableModelDto,
  isCommandCatalogDto,
  isCommandDescriptorDto,
  isDevicePublicKeyJwk,
  isEnrollmentQr,
  isEnrollmentResponse,
  isJsonValue,
  isOpaqueId,
  isPiRpcCommand,
  isPiRpcEvent,
  isPiRpcResponse,
  isPromptAbortResponse,
  isPromptSubmitCommand,
  isPromptSubmitResponse,
  isPushHintPayload,
  isPushPreferences,
  isPushSubscriptionInput,
  isRuntimeControlCommand,
  isRuntimeControlResponse,
  isRuntimeModelCatalogDto,
  isRuntimeOperation,
  isRuntimeStateDto,
  isSessionCardDto,
  isSessionChallengeResponse,
  isSyncMessage,
  isTranscriptBlock,
  isTranscriptPageDto,
  isWebSocketTicketResponse,
} from './guards.js';

export type {
  AcceptEditsGrantDto,
  AbortCommand,
  ApprovalAction,
  ApprovalAuthorityConsumeRequest,
  ApprovalAuthorityConsumeResponse,
  ApprovalAuthorityRequest,
  ApprovalAuthorityRequestResponse,
  ApprovalCardDto,
  ApprovalDecision,
  ApprovalDecisionCommand,
  ApprovalDecisionResponse,
  ApprovalRequestedPayload,
  ApprovalResultPayload,
  ApprovalResultStatus,
  ApplicationSessionResponse,
  AttentionChangedPayload,
  AttentionClass,
  AttentionItemDto,
  AttentionResolutionDto,
  AvailableModelDto,
  CommandCatalogDto,
  CommandDescriptorDto,
  CommandSource,
  DevicePublicKeyJwk,
  EnrollmentQr,
  EnrollmentRequest,
  EnrollmentResponse,
  Envelope,
  FileDiffBlock,
  FollowUpCommand,
  GetEntriesCommand,
  ImageContent,
  JsonObject,
  JsonPrimitive,
  JsonValue,
  PiRpcCommand,
  PiRpcEvent,
  PiRpcEventType,
  PiRpcResponse,
  PlanBlock,
  PushHintPayload,
  PushPreferences,
  PushSubscriptionInput,
  PushSubscriptionKeys,
  PromptAbortResponse,
  PromptCommand,
  PromptSubmitCommand,
  PromptSubmitResponse,
  ReadStateCommand,
  RedactionMetadata,
  ReplayMetadata,
  RuntimeControlCommand,
  RuntimeControlResponse,
  RuntimeModelCatalogDto,
  RuntimeMode,
  RuntimeOperation,
  RuntimeReadCommand,
  RuntimeStateDto,
  SessionCardDto,
  SessionChallengeResponse,
  SteerCommand,
  SyncCursor,
  SyncDelta,
  SyncGap,
  SyncMessage,
  SyncSnapshot,
  TextBlock,
  ThinkingBlock,
  ToolCallBlock,
  ToolResultBlock,
  TranscriptBlock,
  TranscriptPageDto,
  UsageBlock,
  WebSocketTicketResponse,
} from './types.js';
